// @ts-check

// @ts-ignore
window.Packer = (function() {
  'use strict';

  // @ts-ignore
  const SBDL = window.SBDL;
  // @ts-ignore
  const JSZip = window.JSZip;

  function readAsURL(blob) {
    return new Promise((resolve, reject) => {
      const fileReader = new FileReader();
      fileReader.onload = () => {
        resolve(/** @type {string} */ (fileReader.result));
      };
      fileReader.onerror = (e) => {
        reject('Error reading file');
      };
      fileReader.readAsDataURL(blob);
    });
  }

  class FileLoader {
    constructor() {
      this.progress = new Progress();
      this.files = [];
      this.assets = [];
    }

    loadFile(file) {
      return fetch('../' + file.src)
        .then((r) => r.text())
        .then((t) => {
          file.loaded = true;
          file.content = `/* F: ${file.src} */` + t;
        });
    }

    loadAsset(asset) {
      return fetch('../' + asset.src)
        .then((r) => r.blob())
        .then((b) => readAsURL(b))
        .then((url) => {
          asset.loaded = true;
          asset.data = url;
        });
    }

    async loadMissingAssets() {
      const missingFiles = this.files.filter((i) => !i.loaded);
      const missingAssets = this.assets.filter((i) => !i.loaded);

      if (missingFiles.length > 0 || missingAssets.length > 0) {
        this.progress.start();
        await Promise.all([
          ...missingFiles.map((i) => this.loadFile(i)),
          ...missingAssets.map((i) => this.loadAsset(i)),
        ]);
      }

      return {
        scripts: this.files.filter((i) => i.type === 'script').map((i) => i.content).join('\n'),
        styles: this.files.filter((i) => i.type === 'style').map((i) => i.content).join('\n'),
        assets: this.assets,
      };
    }
  }

  class Progress {
    newTask() {}
    endTask() {}
    setProgress(progress) {}
    setCaption(text) {}
    start() {}
  }

  class Packager {
    constructor({ fileLoader }) {
      this.fileLoader = fileLoader;
      this.playerOptions = {
        fullscreenPadding: 0,
        fullscreenMode: 'window',
      };
      this.projectType = null;
      this.projectData = null;
      this.controlsOptions = null;
      this.archiveProgress = new Progress();
    }

    createArchive(files) {
      this.archiveProgress.start();
      const zip = new JSZip();
      for (const file of files) {
        const path = file.path;
        const data = file.data;
        zip.file(path, data);
      }
      return zip.generateAsync({
        type: 'blob',
        compression: 'DEFLATE',
      }, (metadata) => {
        this.archiveProgress.setProgress(metadata.percent);
        this.archiveProgress.setCaption(metadata.currentFile);
      });
    }

    async getProjectTypeById(id) {
      const res = await fetch('https://projects.scratch.mit.edu/' + id);
      if (res.status !== 200) {
        throw new Error('Cannot get project');
      }
      const data = await res.json();
      if ('targets' in data) return 'sb3';
      if ('objName' in data) return 'sb2';
      throw new Error('unknown project type');
    }

    async getProjectById(id) {
      const type = await this.getProjectTypeById(id);
      const result = await SBDL.loadProject(id, type);
      if (result.type !== 'zip') {
        throw new Error('unknown result type: ' + result.type);
      }
      const archive = await this.createArchive(result.files);
      const url = await readAsURL(archive);
      return {
        url: url,
        type: type,
      };
    }

    async loadProjectById(id) {
      const { url, type } = await this.getProjectById(id);
      this.projectData = url;
      this.projectType = type;
    }

    async run() {
      if (!this.projectData || !this.projectType) {
        throw new Error('missing project data or type');
      }

      const { scripts, styles, assets } = await this.fileLoader.loadMissingAssets();

      const generateAssetManagerData = () => {
        return '{' + assets.map((asset) => `"${asset.src}": "${asset.data}"`).join(', ') + '}';
      };

      const body = `<!DOCTYPE html>
<!-- Generated by the forkphorus packager: https://forkphorus.github.io/packager/ -->
<html>
  <head>
    <meta http-equiv="Content-Security-Policy" content="default-src 'unsafe-inline' 'unsafe-eval' data: blob:">
    <style>
${styles}
body {
  background: #000;
  margin: 0;
  overflow: hidden;
}
.player {
  position: absolute;
}
.splash, .error {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: #000;
  display: table;
  color: #fff;
  cursor: default;
}
.error {
  display: none;
}
.splash > div,
.error > div {
  display: table-cell;
  height: 100%;
  text-align: center;
  vertical-align: middle;
}
.progress {
  width: 80%;
  height: 16px;
  border: 1px solid #fff;
  margin: 0 auto;
}
.progress-bar {
  background: #fff;
  width: 10%;
  height: 100%;
}
h1 {
  font: 300 72px Helvetica Neue, Helvetica, Arial, sans-serif;
  margin: 0 0 16px;
}
p {
  font: 300 24px/1.5 Helvetica Neue, Helvetica, Arial, sans-serif;
  margin: 0;
  color: rgba(255, 255, 255, .6);
}
.error a {
  color: #fff;
}
    </style>
  </head>
  <body>

    <div class="player"></div>
    <div class="splash">
      <div>
        <h1>forkphorus</h1>
        <div class="progress">
          <div class="progress-bar"></div>
        </div>
      </div>
    </div>
    <div class="error">
      <div>
        <h1>Internal Error</h1>
        <p class="error-report"></p>
      </div>
    </div>

    <script>
${scripts}
(function () {
  'use strict';

  var splash = document.querySelector('.splash');
  var error = document.querySelector('.error');
  var progressBar = document.querySelector('.progress');
  var progressBarFill = document.querySelector('.progress-bar');

  var splash = document.querySelector('.splash');
  var error = document.querySelector('.error');
  var progressBar = document.querySelector('.progress');
  var progressBarFill = document.querySelector('.progress-bar');

  var player = new P.player.Player();
  player.setOptions({ theme: 'dark' });
  var errorHandler = new P.player.ErrorHandler(player, {
    container: document.querySelector('.error-report'),
  });
  player.onprogress.subscribe(function(progress) {
    progressBarFill.style.width = (10 + progress * 90) + '%';
  });
  player.onerror.subscribe(function(e) {
    player.exitFullscreen();
    error.style.display = 'table';
  });
  document.querySelector('.player').appendChild(player.root);

  document.addEventListener('touchmove', function(e) {
    e.preventDefault();
  });

  P.io.setAssetManager(new class {
    constructor() {
      // Assets...
      this.data = ${generateAssetManagerData()};
    }

    loadSoundbankFile(src) {
      return this.fetch('soundbank/' + src).then(function(e) { return e.arrayBuffer(); });
    }

    loadFont(src) {
      return this.fetch(src).then(function(e) { return e.blob(); });
    }

    fetch(u) {
      return fetch(this.data[u]);
    }
  });

  // Project data...
  var type = '${this.projectType}';
  var project = '${this.projectData}';

  // Options...
  player.setOptions(${JSON.stringify(this.playerOptions)});
  var controlsOptions = ${JSON.stringify(this.controlsOptions)};
  if (controlsOptions) {
    player.addControls(controlsOptions);
  }

  fetch(project)
    .then(function(request) { return request.arrayBuffer(); })
    .then(function(buffer) { return player.loadProjectFromBuffer(buffer, type); })
    .then(function() {
      player.enterFullscreen();
      splash.style.display = 'none';
    })
    .catch(function(e) {
      player.handleError(e);
    });
}());
    </script>
  </body>
</html>`;
      return body;
    }
  }

  return {
    FileLoader,
    Packager,
  };

}());
